[[MUMPS]]
arch = "aarch64"
git-tree-sha1 = "eb1929f77f4d6647cf1dc2bce15b64c3b8618fea"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "macos"

    [[MUMPS.download]]
    sha256 = "ec3fd6ff0ed8e44a348dbff06afb96c710a8b270fdd8be97b2a31afdc53badc3"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_jll.jl/releases/download/MUMPS-v5.8.2+0/MUMPS.v5.8.2.aarch64-apple-darwin-libgfortran5-mpi+mpich.tar.gz"
[[MUMPS]]
arch = "aarch64"
git-tree-sha1 = "33a555eefdf05fce870c8996339171d325d0388c"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "macos"

    [[MUMPS.download]]
    sha256 = "aa871e74e5486aab40ef1112eebd64c585f3c10cce8d8030fda63f7316815e45"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_jll.jl/releases/download/MUMPS-v5.8.2+0/MUMPS.v5.8.2.aarch64-apple-darwin-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MUMPS]]
arch = "aarch64"
git-tree-sha1 = "20b416a4c46e42eaa7e6ff6896bdaabeb8163187"
lazy = true
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "macos"

    [[MUMPS.download]]
    sha256 = "8d6e2d24cdaeafdfb4d60d9b77d2dc6839c9056f50ae5240feec6a55c73d33a7"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_jll.jl/releases/download/MUMPS-v5.8.2+0/MUMPS.v5.8.2.aarch64-apple-darwin-libgfortran5-mpi+openmpi.tar.gz"
[[MUMPS]]
arch = "aarch64"
git-tree-sha1 = "b845b6e1182e7870cd5bb25f793b5d22fb95241c"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[MUMPS.download]]
    sha256 = "2e1aa586b3c3137e88a66b79162a58beb81ae297ca954a65563ccbd00b825407"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_jll.jl/releases/download/MUMPS-v5.8.2+0/MUMPS.v5.8.2.aarch64-linux-gnu-libgfortran5-mpi+mpich.tar.gz"
[[MUMPS]]
arch = "aarch64"
git-tree-sha1 = "d20ce96c0921c84c39ed349eb1ac83f8a943c19f"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MUMPS.download]]
    sha256 = "fa2bc244f7d63a8285f802b36a1f0825a8f56645e2b1c7a39029dd433e03a5b6"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_jll.jl/releases/download/MUMPS-v5.8.2+0/MUMPS.v5.8.2.aarch64-linux-gnu-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MUMPS]]
arch = "aarch64"
git-tree-sha1 = "8fe60d9c4f07399a30fbdd43bd5411e3887d63ab"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[MUMPS.download]]
    sha256 = "f87e4c353fcfd4fe6eceff5ba9afdbc2f4d34ae8436692975598bc0f3a2e5c01"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_jll.jl/releases/download/MUMPS-v5.8.2+0/MUMPS.v5.8.2.aarch64-linux-gnu-libgfortran5-mpi+openmpi.tar.gz"
[[MUMPS]]
arch = "aarch64"
git-tree-sha1 = "df2444830530c5ee19a1b6eeb13b043758e31e7d"
lazy = true
libc = "musl"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[MUMPS.download]]
    sha256 = "ea19efe085771728648f2a1eb5f62b929c795c7ae2b1be2d168807d13eeee618"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_jll.jl/releases/download/MUMPS-v5.8.2+0/MUMPS.v5.8.2.aarch64-linux-musl-libgfortran5-mpi+mpich.tar.gz"
[[MUMPS]]
arch = "aarch64"
git-tree-sha1 = "971bbcb38194f1359993b9f0b73df6bd473e4f1c"
lazy = true
libc = "musl"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[MUMPS.download]]
    sha256 = "052e3009e38c82d00ac3332f44b79fcefe3c72bf4f84e108156582cb269c267f"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_jll.jl/releases/download/MUMPS-v5.8.2+0/MUMPS.v5.8.2.aarch64-linux-musl-libgfortran5-mpi+openmpi.tar.gz"
[[MUMPS]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "fae811437ea97e6d3c26b8a7a989bb15edaef064"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[MUMPS.download]]
    sha256 = "a9356aee0bff841451c58ac465f29dc99f111bba9c2edd0516424e9ec0e9be59"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_jll.jl/releases/download/MUMPS-v5.8.2+0/MUMPS.v5.8.2.armv6l-linux-gnueabihf-libgfortran5-mpi+mpich.tar.gz"
[[MUMPS]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ca38e4c3156510bd0295387ac368b793997dee60"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MUMPS.download]]
    sha256 = "a9ec8dddaf8549aa8bcde7a0afb8a66fc732f0311227f243a8c258d34841f47e"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_jll.jl/releases/download/MUMPS-v5.8.2+0/MUMPS.v5.8.2.armv6l-linux-gnueabihf-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MUMPS]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "de790acd63e794e4a3cf8c807e7f031b6be761f1"
lazy = true
libc = "musl"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[MUMPS.download]]
    sha256 = "5a2f1b6c3a169c76ebb5aace90905dcd1cbe89698aa5c0a7cebe45479319dbc6"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_jll.jl/releases/download/MUMPS-v5.8.2+0/MUMPS.v5.8.2.armv6l-linux-musleabihf-libgfortran5-mpi+mpich.tar.gz"
[[MUMPS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "41b180bfc0b8fcc490797b4ef68814b9a38d2d4b"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[MUMPS.download]]
    sha256 = "9b2de7e699fe12bd5a7cc59dd664b0ab0f6d8b5fc401bb9af76da06c453eed8a"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_jll.jl/releases/download/MUMPS-v5.8.2+0/MUMPS.v5.8.2.armv7l-linux-gnueabihf-libgfortran5-mpi+mpich.tar.gz"
[[MUMPS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "454e7fe60996c2801635a071e4525250685e23a8"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MUMPS.download]]
    sha256 = "050523738846f49a9b073f499c5490515b2e83a6d80c63cf23fbc6c132e236c4"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_jll.jl/releases/download/MUMPS-v5.8.2+0/MUMPS.v5.8.2.armv7l-linux-gnueabihf-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MUMPS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c4284d9e79d34d1fb52d0bf270b1618917ac0883"
lazy = true
libc = "musl"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[MUMPS.download]]
    sha256 = "17010f2d7c523315d072ea3f553da5029116ecafb3f57529f08da4a3f69fe00c"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_jll.jl/releases/download/MUMPS-v5.8.2+0/MUMPS.v5.8.2.armv7l-linux-musleabihf-libgfortran5-mpi+mpich.tar.gz"
[[MUMPS]]
arch = "i686"
git-tree-sha1 = "e5bc151da813b85effc3e6057664827fafd234f5"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[MUMPS.download]]
    sha256 = "9cc22d95e7f75c7bd7283105cff571ce9bcf60a10ae2aada6dba0b93d30ca033"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_jll.jl/releases/download/MUMPS-v5.8.2+0/MUMPS.v5.8.2.i686-linux-gnu-libgfortran5-mpi+mpich.tar.gz"
[[MUMPS]]
arch = "i686"
git-tree-sha1 = "9f38373b6bb319e11ec307714d2c5ef167897e16"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MUMPS.download]]
    sha256 = "f4104fe7e25883faa66e2d49c6475c341f21541a032fa1a629106dba5781c5b3"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_jll.jl/releases/download/MUMPS-v5.8.2+0/MUMPS.v5.8.2.i686-linux-gnu-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MUMPS]]
arch = "i686"
git-tree-sha1 = "e223a21be683407d2764925cb2107253f5b56c00"
lazy = true
libc = "musl"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[MUMPS.download]]
    sha256 = "1db03be2e17d6649fc5e60ee54f87c869a7649acb4f8ac865fe1f85d8872de17"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_jll.jl/releases/download/MUMPS-v5.8.2+0/MUMPS.v5.8.2.i686-linux-musl-libgfortran5-mpi+mpich.tar.gz"
[[MUMPS]]
arch = "i686"
git-tree-sha1 = "8c17be1a8d2d0f92bae2da0064aa63c4b169ce9f"
lazy = true
libgfortran_version = "5.0.0"
mpi = "microsoftmpi"
os = "windows"

    [[MUMPS.download]]
    sha256 = "6b82bae21461970defd8251bb034a8628e827a0261ac1dda0146a24d86ab1c8d"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_jll.jl/releases/download/MUMPS-v5.8.2+0/MUMPS.v5.8.2.i686-w64-mingw32-libgfortran5-mpi+microsoftmpi.tar.gz"
[[MUMPS]]
arch = "powerpc64le"
git-tree-sha1 = "16bc70aaa5d8d0a773ad27848ae9076ba0d2ce93"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[MUMPS.download]]
    sha256 = "386db9cb631dd469a634bfcf35bd0ff9bc497adbe597fddc107f9fbfd2b748ba"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_jll.jl/releases/download/MUMPS-v5.8.2+0/MUMPS.v5.8.2.powerpc64le-linux-gnu-libgfortran5-mpi+mpich.tar.gz"
[[MUMPS]]
arch = "powerpc64le"
git-tree-sha1 = "9398558f46900d22664cd6ebe3d4387dae28d3aa"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MUMPS.download]]
    sha256 = "8c88685549060b792e08990660d12daff2b5a9fd97ef81c57596806029861f57"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_jll.jl/releases/download/MUMPS-v5.8.2+0/MUMPS.v5.8.2.powerpc64le-linux-gnu-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MUMPS]]
arch = "powerpc64le"
git-tree-sha1 = "cd2ccefc67a376d3042b304a3e26705747e5ab26"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[MUMPS.download]]
    sha256 = "28286edcc0114a184b7ac287aa497a0f2ea71ae619934202b5ab5ed426b5682b"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_jll.jl/releases/download/MUMPS-v5.8.2+0/MUMPS.v5.8.2.powerpc64le-linux-gnu-libgfortran5-mpi+openmpi.tar.gz"
[[MUMPS]]
arch = "x86_64"
git-tree-sha1 = "364c48bbd69b450d77197bf95779569e43ce9f51"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "macos"

    [[MUMPS.download]]
    sha256 = "cbd1257562688750c3569c4faeb99968af78a6aecc57f018cd54191d35c1621b"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_jll.jl/releases/download/MUMPS-v5.8.2+0/MUMPS.v5.8.2.x86_64-apple-darwin-libgfortran5-mpi+mpich.tar.gz"
[[MUMPS]]
arch = "x86_64"
git-tree-sha1 = "f1775cb264d7405cfb082d0ad1e362333ce9d09b"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "macos"

    [[MUMPS.download]]
    sha256 = "98fa240516584385228ff8b74e48e2b54641ba8ec97a3dfd2968e559b5385f73"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_jll.jl/releases/download/MUMPS-v5.8.2+0/MUMPS.v5.8.2.x86_64-apple-darwin-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MUMPS]]
arch = "x86_64"
git-tree-sha1 = "21054e0a3785e16106552f911d26318cc1c7336f"
lazy = true
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "macos"

    [[MUMPS.download]]
    sha256 = "a1a66467b947fb4b41dbe776e5756945388b7b73b15da9b422bbcc34193618a2"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_jll.jl/releases/download/MUMPS-v5.8.2+0/MUMPS.v5.8.2.x86_64-apple-darwin-libgfortran5-mpi+openmpi.tar.gz"
[[MUMPS]]
arch = "x86_64"
git-tree-sha1 = "6891c75e8311c105b128ee26ef7d8f53dacee7fa"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[MUMPS.download]]
    sha256 = "c308336822b03974defdf23f98cbcb7764694aa5af71d17f38707e866bdd6685"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_jll.jl/releases/download/MUMPS-v5.8.2+0/MUMPS.v5.8.2.x86_64-linux-gnu-libgfortran5-mpi+mpich.tar.gz"
[[MUMPS]]
arch = "x86_64"
git-tree-sha1 = "1150017a434f059dae0380fd0e2f090aa2157af9"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MUMPS.download]]
    sha256 = "a5e42e2677e5e7983ce179b2d4e3691fe07923248171e23b0f4acaa67892c3ee"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_jll.jl/releases/download/MUMPS-v5.8.2+0/MUMPS.v5.8.2.x86_64-linux-gnu-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MUMPS]]
arch = "x86_64"
git-tree-sha1 = "a14a8b0d12b56242cf1330941ec134ecd8c5131c"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[MUMPS.download]]
    sha256 = "cbb9f890c089b5e019986e69b09b47a5c2879027e94fb5947927339efd9bafb8"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_jll.jl/releases/download/MUMPS-v5.8.2+0/MUMPS.v5.8.2.x86_64-linux-gnu-libgfortran5-mpi+openmpi.tar.gz"
[[MUMPS]]
arch = "x86_64"
git-tree-sha1 = "2248cf9faa517c6d7e134df17d38de885ed5f88a"
lazy = true
libc = "musl"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[MUMPS.download]]
    sha256 = "6962c8157ca8ffaea820788463835a5ca9df647c9521d60f88a52b7ad0ac06bf"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_jll.jl/releases/download/MUMPS-v5.8.2+0/MUMPS.v5.8.2.x86_64-linux-musl-libgfortran5-mpi+mpich.tar.gz"
[[MUMPS]]
arch = "x86_64"
git-tree-sha1 = "5328f8c7fa60a18e3307960cede920df56eb9111"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "freebsd"

    [[MUMPS.download]]
    sha256 = "3ea165676a29daccdda6d9127762739ccc1e19aa4fcb8079cccc4050be561b6f"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_jll.jl/releases/download/MUMPS-v5.8.2+0/MUMPS.v5.8.2.x86_64-unknown-freebsd-libgfortran5-mpi+mpich.tar.gz"
[[MUMPS]]
arch = "x86_64"
git-tree-sha1 = "82df2d93cbce04e61f49d03f175f866399e9d926"
lazy = true
libgfortran_version = "5.0.0"
mpi = "microsoftmpi"
os = "windows"

    [[MUMPS.download]]
    sha256 = "21620424b2b6df56d45f06c7841f5df95b52debf578dcf4e49d5094b89a7d107"
    url = "https://github.com/JuliaBinaryWrappers/MUMPS_jll.jl/releases/download/MUMPS-v5.8.2+0/MUMPS.v5.8.2.x86_64-w64-mingw32-libgfortran5-mpi+microsoftmpi.tar.gz"
